FROM node:22-bookworm

RUN apt-get update && apt-get install -y \
  texlive-latex-base \
  texlive-latex-recommended \
  texlive-fonts-recommended \
  texlive-lang-spanish \
  texlive-latex-extra \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY apps/api/package*.json ./
RUN npm ci

COPY apps/api ./

RUN npx prisma generate

EXPOSE 8080

CMD ["npm", "start"]