FROM node:22-bookworm

RUN apt-get update && apt-get install -y \
  texlive-latex-base \
  texlive-latex-recommended \
  texlive-fonts-recommended \
  texlive-lang-spanish \
  texlive-latex-extra \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY apps/api/package*.json ./
RUN npm ci

COPY apps/api ./

EXPOSE 8080

CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm start"]